services:
  nodejs:
    build: .
    restart: unless-stopped
    networks:
      - app-network
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/app/aiPBX
      - node_modules:/app/aiPBX/node_modules
    ports:
      - "7003:7003"

#  nginx:
#    image: nginx:alpine
#    restart: unless-stopped
#    networks:
#      - app-network
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#      - /etc/letsencrypt/live/speech.krasterisk.ru:/etc/letsencrypt/live/speech.krasterisk.ru

volumes:
  node_modules:

networks:
  app-network:
    driver: bridge
